// Generated by CoffeeScript 1.6.2
var exec;

exec = require('child_process').exec;

task('build', 'Build project coffeescript files.', function() {
  exec('coffee -cm app.coffee', function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
  return exec('coffee -cm public/', function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
});

task('watch', 'Execute a build that watches!', function() {
  exec('coffee -wcm app.coffee', function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
  return exec('coffee -wcm public/', function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
});
