// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, fs, port;

  express = require('express');

  fs = require('fs');

  app = express();

  port = process.env.PORT || 8080;

  app.configure(function() {
    app.set("view options", {
      layout: false,
      pretty: true
    });
    app.use(express.favicon());
    app.use(express["static"](__dirname + '/public'));
    return app.use(express.bodyParser());
  });

  app.get('/', function(req, res) {
    return res.sendfile("index.html", {
      root: './public'
    });
  });

  app.get('/raw/:file', function(req, res) {
    console.log("Received request for: ", req.params.file);
    return res.sendfile(req.params.file, {
      root: './literals'
    });
  });

  app.get('/:file', function(req, res) {
    return res.sendfile('literator.html', {
      root: './public'
    });
  });

  app.post('/raw/:file', function(req, res) {
    console.log("Requesting to put file ", req.params.file);
    return fs.writeFile("./literals/" + req.params.file, req.body.data, function(err) {
      if (err) {
        throw err;
      }
      return console.log("File saved successfully.");
    });
  });

  app.post("/new", function(req, res) {
    var encoder, i, index, name, _i;

    name = "";
    encoder = "abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUWXYZ";
    for (i = _i = 1; _i <= 5; i = ++_i) {
      index = Math.floor(encoder.length * Math.random());
      name += encoder[index];
    }
    console.log("chose new file name: " + name);
    fs.writeFile("./literals/" + name, req.body.data, function(err) {
      if (err) {
        throw err;
      }
      return console.log("New file saved successfully.");
    });
    return res.send(name);
  });

  app.listen(port);

  console.log("Server started.");

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
