// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('.drop_zone').on('dragover', function(e) {
      e.preventDefault();
      return e.stopPropagation();
    });
    $('.drop_zone').on('drop', function(e) {
      var f, files, reader, _i, _len, _results;
      e.preventDefault();
      e.stopPropagation();
      console.log("Dropped!");
      console.log(files = e.originalEvent.dataTransfer.files);
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        f = files[_i];
        console.log("Loading file " + f.name + "...");
        reader = new FileReader();
        reader.onload = function(file) {
          return console.log(file);
        };
        _results.push(console.log(reader.readAsText(f)));
      }
      return _results;
    });
    return $('.drop_zone').on('dragenter', function(e) {
      e.preventDefault();
      e.stopPropagation();
      return console.log("Entered!");
    });
  });

}).call(this);
